workflows: Make `Tests` non-required
As we've been constantly hitting:
```
 failures:

---- mount_linux::tests::test_setup_loop_dev stdout ----
thread 'mount_linux::tests::test_setup_loop_dev' panicked at crates/shim/src/mount_linux.rs:1174:9:
assertion failed: result.is_ok()
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace

failures:
    mount_linux::tests::test_setup_loop_dev
```

Signed-off-by: Fabiano Fidêncio <fidencio@northflank.com>